## Lectura del documento

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../Archivos-Analisis/files-tarea-m40/kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

## Se realizara un cambio de tipo de dato a las siguientes columnas:
- Date 
- Bathrooms
- Floors

Ya que el tipo de dato es float, cosa que no debe de ser asi, ya que a como se maneja la imformacion, deben de ser el tipo entero

En caso de Date, este debe de cambiarse a un mejor formato, ejem: 'DD/MM/YYYY', ya que a la hora de trabajar con looker studio y querer manejar graficos con fechas, este solo acepta el formato antes mencionado

In [4]:
# Convertimos las columnas bathrooms y floors a tipo entero
df['bathrooms'] = df['bathrooms'].astype('int64')
df['floors'] = df['floors'].astype('int64')

df.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms          int64
sqft_living        int64
sqft_lot           int64
floors             int64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [5]:
# Convertimos la columna a formato tipo datetime y con la serie DD/MM/YYYY
df['date'] = pd.to_datetime(df['date'], format='%Y%m%dT%H%M%S').dt.strftime('%d/%m/%Y')

df['date'].head()

0    13/10/2014
1    09/12/2014
2    25/02/2015
3    09/12/2014
4    18/02/2015
Name: date, dtype: object

In [6]:
df.sample(10)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
11376,5694501195,11/05/2015,438600.0,1,1,720,2500,1,0,0,...,7,720,0,1910,0,98103,47.6597,-122.345,1520,3750
19101,5126210360,22/10/2014,570000.0,4,2,3420,115434,2,0,0,...,9,3420,0,1989,0,98038,47.3932,-121.988,3250,111513
14801,1972201960,25/08/2014,513000.0,3,2,1500,1312,3,0,0,...,8,1500,0,2007,0,98103,47.6534,-122.346,1500,1282
1359,3526039116,18/11/2014,549000.0,3,1,2000,6130,1,0,0,...,8,1120,880,1951,0,98117,47.6925,-122.388,2140,7150
10779,2600110710,19/08/2014,602000.0,3,2,1580,11580,1,0,0,...,8,1580,0,1979,0,98006,47.5503,-122.155,2630,10009
3900,6821102352,08/10/2014,330000.0,2,1,880,1753,2,0,0,...,7,880,0,1945,0,98199,47.6475,-122.397,1010,1748
11838,6743700060,14/07/2014,585000.0,4,1,3140,12519,1,0,0,...,7,2320,820,1951,1983,98033,47.6941,-122.173,2240,7308
5558,9264910280,22/04/2015,280500.0,4,2,2660,7754,1,0,0,...,8,1590,1070,1986,0,98023,47.3078,-122.337,2250,7754
10640,3574800860,07/10/2014,440000.0,3,1,2350,7641,1,0,0,...,7,1510,840,1978,0,98034,47.7307,-122.219,2190,7500
14928,1513800170,02/04/2015,392500.0,3,1,930,6572,1,0,0,...,7,930,0,1952,0,98115,47.6889,-122.301,960,5840

## Detectamos los calores Nulos

In [7]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

No se detectaron nulos

## Comparacion de analisis obtenido

In [12]:
# Agrupar por zipcode y año de construcción, calcular métricas y ordenar por precio promedio descendente
analysis = df.groupby(['zipcode', 'yr_built']).agg({
    'price': 'mean',
    'bedrooms': 'mean',
    'bathrooms': 'mean'
}).reset_index()

analysis.columns = ['zipcode', 'yr_built', 'precio_promedio', 'bedrooms_promedio', 'bathrooms_promedio']
analysis = analysis.sort_values('precio_promedio', ascending=False).round(2).head(50)

analysis

,zipcode,yr_built,precio_promedio,bedrooms_promedio,bathrooms_promedio
215,98004,1940,7062500.00,5.00,4.00
4214,98155,2004,4500000.00,5.00,5.00
1516,98039,2001,4204500.00,4.75,5.00
1520,98039,2008,4000000.00,4.00,5.00
1515,98039,2000,3710000.00,4.00,3.00
1512,98039,1990,3640900.00,4.00,3.00
1518,98039,2005,3635000.00,5.00,6.00
1522,98039,2014,3418800.00,5.00,5.00
465,98008,1989,3300000.00,5.00,4.00
1369,98034,1957,3070000.00,3.00,2.00
469,98008,2001,2989000.00,3.00,2.00
1573,98040,1991,2958333.33,5.33,4.33
1514,98039,1996,2950000.00,4.00,3.00
2881,98107,2010,2945000.00,5.00,4.00
3000,98109,1991,2900000.00,4.00,3.00
1521,98039,2013,2900000.00,5.00,4.00
4415,98177,1994,2880500.00,4.00,2.00
1495,98039,1952,2750000.00,4.00,3.00
385,98006,2003,2744000.00,4.50,4.50
1511,98039,1989,2720000.00,4.00,3.00
1508,98039,1985,2590000.00,4.50,3.50
1504,98039,1975,2575000.00,5.00,3.00
272,98004,2006,2516666.67,4.33,4.00
1583,98040,2005,2502500.00,3.50,3.50
1526,98040,1931,2485000.00,4.00,2.00
2868,98107,1993,2475000.00,3.00,3.00
3043,98112,1935,2453500.00,4.00,3.00
1513,98039,1992,2450000.00,7.00,4.00
471,98008,2007,2415000.00,4.67,3.67
3530,98119,1999,2400000.00,6.00,4.00
267,98004,2001,2381250.00,4.00,3.00
1525,98040,1930,2367000.00,3.00,2.00
1271,98033,1907,2350000.00,4.00,2.00
270,98004,2004,2312233.33,4.67,3.33
275,98004,2009,2311166.67,3.67,3.67
1582,98040,2004,2298000.00,4.00,4.00
252,98004,1983,2288000.00,4.00,2.00
1578,98040,1999,2283333.33,4.67,3.67
1576,98040,1996,2280000.00,3.50,3.00
1821,98053,1999,2280000.00,7.00,8.00
1565,98040,1983,2258666.67,4.00,3.00
4417,98177,1997,2237500.00,3.50,3.50
3042,98112,1933,2225000.00,3.00,4.00
1729,98052,1952,2200000.00,5.00,4.00
1517,98039,2004,2187730.00,4.00,4.00
279,98004,2013,2179285.71,4.71,3.71
4691,98199,1996,2160000.00,3.00,3.00
248,98004,1978,2149960.00,4.67,3.33
4705,98199,2010,2125000.00,4.50,3.50
3014,98112,1904,2092500.00,5.50,2.50

In [13]:
analysis_zipcode_only = df.groupby(['zipcode']).agg({
    'price': 'mean',
    'bedrooms': 'mean',
    'bathrooms': 'mean'
}).reset_index()

analysis_zipcode_only.columns = ['zipcode', 'precio_promedio', 'bedrooms_promedio', 'bathrooms_promedio']
analysis_zipcode_only = analysis_zipcode_only.sort_values('precio_promedio', ascending=False).round(2).head(50)

analysis_zipcode_only

    zipcode  precio_promedio  bedrooms_promedio  bathrooms_promedio
24    98039       2160606.60               4.06                2.84
3     98004       1355927.08               3.85                2.10
25    98040       1194230.02               4.03                2.31
48    98112       1095499.34               3.51                2.03
41    98102        901258.27               3.22                1.91
47    98109        879623.62               3.19                1.85
43    98105        862825.23               3.58                1.78
5     98006        859684.78               3.84                2.13
53    98119        849448.02               3.26                1.87
4     98005        810164.88               3.85                2.01
21    98033        803719.52               3.56                1.92
69    98199        791820.81               3.21                1.80
38    98075        790576.65               3.86                2.29
37    98074        685605.78               3.63                2.07
39    98077        682774.88               3.62                2.06
29    98053        678163.06               3.21                2.05
65    98177        676185.39               3.40                1.71
7     98008        645507.38               3.73                1.67
28    98052        645231.46               3.62                1.90
54    98122        634360.18               3.17                1.78
49    98115        619900.55               3.20                1.56
50    98116        618634.17               3.07                1.65
6     98007        617105.09               3.82                1.77
15    98027        616990.59               3.54                2.09
17    98029        612653.61               3.43                2.13
59    98144        594547.65               3.22                1.72
42    98103        584919.21               3.06                1.66
14    98024        580526.79               3.30                1.83
45    98107        579053.42               3.00                1.74
51    98117        576795.01               3.02                1.52
36    98072        569958.47               3.45                1.82
58    98136        551688.67               2.93                1.57
34    98065        527961.20               3.52                2.09
22    98034        521652.86               3.47                1.72
33    98059        493552.53               3.72                1.89
9     98011        490351.47               3.55                1.85
35    98070        487479.63               2.75                1.53
55    98125        469455.77               3.20                1.51
63    98166        464231.84               3.38                1.56
16    98028        462480.04               3.48                1.73
10    98014        455617.11               3.00                1.65
27    98045        439471.08               3.23                1.70
11    98019        424788.75               3.36                1.86
56    98126        424706.36               2.84                1.43
62    98155        423725.70               3.32                1.51
8     98010        423665.99               3.29                1.62
31    98056        420890.55               3.44                1.68
52    98118        417637.43               3.13                1.53
57    98133        386997.40               3.13                1.43
23    98038        366867.60               3.44                1.95

In [17]:
# Convertir square feet a metros cuadrados (1 sq ft = 0.092903 m²)
# Calcular precio por m² agrupado por zipcode
precio_por_m2 = df.groupby('zipcode').apply(
    lambda x: (x['price'].sum() / (x['sqft_living'].sum() * 0.092903)).round(2)
).reset_index()

precio_por_m2.columns = ['zipcode', 'precio_por_m2']
precio_por_m2 = precio_por_m2.sort_values('precio_por_m2', ascending=False)

precio_por_m2

C:\Users\RyanHz\AppData\Local\Temp\ipykernel_8672\4215656646.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  precio_por_m2 = df.groupby('zipcode').apply(

    zipcode  precio_por_m2
24    98039        6118.71
3     98004        5017.18
48    98112        4719.12
47    98109        4607.89
53    98119        4558.90
..      ...            ...
18    98030        1624.53
0     98001        1590.10
20    98032        1556.30
13    98023        1551.15
1     98002        1549.27

[70 rows x 2 columns]

## Guardado del archivo

In [13]:
df.to_csv('bienes_raices_clean.csv', index=False)

In [ ]:
df.to_sql('bienes_raices_clean', con=engine, if_exists='replace', index=False)